#!/bin/bash

set -u
set -e

if [ $# -ne 1 ]; then
  (
    echo "ERROR: Invalid number of arguments $#"
    echo "Usage: $0 <prob-directory>"
    echo ""
    echo "<prob-directory>  is where you want pstmd to ls and write the log"

  ) >&2

  exit 1
fi

MON_FILE=$1

cd `dirname $MON_FILE`

while :; do
  ls . > /dev/null
  date "+%Y-%m-%d_%H-%M%t%S" | tee -a `basename $MON_FILE`

  sleep 1
done
