#!/bin/bash

set -u
set -e

if [ $# -ne 1 ]; then
  (
    echo "ERROR: Invalid number of arguments $#"
    echo "Usage: $0 <prob-directory>"
    echo ""
    echo "<prob-directory>  is where you want the daemon time ls and log"
    echo ""
    echo "The daemon has collision detection so it is safe to CRON them."

  ) >&2

  exit 1
fi

MON_FILE=$1
MON_FILE_DIR=$(dirname $MON_FILE)

mkdir -p $MON_FILE_DIR 2> /dev/null && true
cd $MON_FILE_DIR
mon_file_basename=`basename $MON_FILE`

last_cleanup="$mon_file_basename-last-cleanup"
[ -e $last_cleanup ] || touch $last_cleanup

while :; do

  # Log
  date "+%Y-%m-%d_%H-%M%t%S" | tee -a $mon_file_basename

  # Cleanup every hour
  if [ $(expr `date +%s` - `stat -c %Y $last_cleanup`) -gt 3600 ]; then
    # Keep only (1 month + slowdonwns) of logs, short range for testing
    tmpfile=$(mktemp)
    tail -n 2629743 $mon_file_basename > $tmpfile
    mv $tmpfile $mon_file_basename
    touch $last_cleanup
  fi

  # Collision detection 1/2
  before_sleep=`tail $mon_file_basename`
 
  # Probe 
  ls . > /dev/null
  sleep 1

  # Collision detection 2/2
  after_sleep=`tail $mon_file_basename`
  if [ "$before_sleep" != "$after_sleep" ] ; then
    break
  fi

done
